
#ifndef OCTETOS_CC_TT_LITERALS_HH
#define OCTETOS_CC_TT_LITERALS_HH


/*
 * Copyright (C) 2022 Azael Reyes <azael.devel@gmail.com>
 * 
 * octetos-CC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * octetos-CC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#define LENGTH_TT(TABLE) sizeof (TABLE) / sizeof (TABLE[0])
#define TABLE(T) T,sizeof (T) / sizeof (T[0])

#include "../tt.hh"


namespace oct::cc::tt
{
	
	static const a::Transition char_literal[][tt::MAX_SIMBOLS] = {
	//0
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Prev_Eat,0,Tokens::none},//tab
			{Indicator::Prev_Eat,0,Tokens::none},//new line
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Prev_Eat,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::None,1,Tokens::none},//'
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//1 : '(char)?
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::None,2,Tokens::none},//' '
			{Indicator::None,2,Tokens::none},//!
			{Indicator::None,2,Tokens::none},//"
			{Indicator::None,2,Tokens::none},//#
			{Indicator::None,2,Tokens::none},//$
			{Indicator::None,2,Tokens::none},//%
			{Indicator::None,2,Tokens::none},//&
			{Indicator::None,2,Tokens::none},//'
			{Indicator::None,2,Tokens::none},//(
			{Indicator::None,2,Tokens::none},//)
			{Indicator::None,2,Tokens::none},//*
			{Indicator::None,2,Tokens::none},//+
			{Indicator::None,2,Tokens::none},//
			{Indicator::None,2,Tokens::none},//-
			{Indicator::None,2,Tokens::none},//.
			{Indicator::None,2,Tokens::none},// /
			{Indicator::None,2,Tokens::none},//0
			{Indicator::None,2,Tokens::none},//1
			{Indicator::None,2,Tokens::none},//2
			{Indicator::None,2,Tokens::none},//3
			{Indicator::None,2,Tokens::none},//4
			{Indicator::None,2,Tokens::none},//5
			{Indicator::None,2,Tokens::none},//6
			{Indicator::None,2,Tokens::none},//7
			{Indicator::None,2,Tokens::none},//8
			{Indicator::None,2,Tokens::none},//9
			{Indicator::None,2,Tokens::none},//:
			{Indicator::None,2,Tokens::none},//;
			{Indicator::None,2,Tokens::none},//<
			{Indicator::None,2,Tokens::none},//=
			{Indicator::None,2,Tokens::none},//>
			{Indicator::None,2,Tokens::none},//?
			{Indicator::None,2,Tokens::none},//@
			{Indicator::None,2,Tokens::none},//A
			{Indicator::None,2,Tokens::none},//B
			{Indicator::None,2,Tokens::none},//C
			{Indicator::None,2,Tokens::none},//D
			{Indicator::None,2,Tokens::none},//E
			{Indicator::None,2,Tokens::none},//F
			{Indicator::None,2,Tokens::none},//G
			{Indicator::None,2,Tokens::none},//H
			{Indicator::None,2,Tokens::none},//I
			{Indicator::None,2,Tokens::none},//J
			{Indicator::None,2,Tokens::none},//K
			{Indicator::None,2,Tokens::none},//L
			{Indicator::None,2,Tokens::none},//M
			{Indicator::None,2,Tokens::none},//N
			{Indicator::None,2,Tokens::none},//O
			{Indicator::None,2,Tokens::none},//P
			{Indicator::None,2,Tokens::none},//Q
			{Indicator::None,2,Tokens::none},//R
			{Indicator::None,2,Tokens::none},//S
			{Indicator::None,2,Tokens::none},//T
			{Indicator::None,2,Tokens::none},//U
			{Indicator::None,2,Tokens::none},//V
			{Indicator::None,2,Tokens::none},//W
			{Indicator::None,2,Tokens::none},//X
			{Indicator::None,2,Tokens::none},//Y
			{Indicator::None,2,Tokens::none},//Z
			{Indicator::None,2,Tokens::none},//[
			{Indicator::None,2,Tokens::none},//contra diagonal
			{Indicator::None,2,Tokens::none},//]
			{Indicator::None,2,Tokens::none},//
			{Indicator::None,2,Tokens::none},//_
			{Indicator::None,2,Tokens::none},//`
			{Indicator::None,2,Tokens::none},//a
			{Indicator::None,2,Tokens::none},//b
			{Indicator::None,2,Tokens::none},//c
			{Indicator::None,2,Tokens::none},//d
			{Indicator::None,2,Tokens::none},//e
			{Indicator::None,2,Tokens::none},//f
			{Indicator::None,2,Tokens::none},//g
			{Indicator::None,2,Tokens::none},//h
			{Indicator::None,2,Tokens::none},//i
			{Indicator::None,2,Tokens::none},//j
			{Indicator::None,2,Tokens::none},//k
			{Indicator::None,2,Tokens::none},//l
			{Indicator::None,2,Tokens::none},//m
			{Indicator::None,2,Tokens::none},//n
			{Indicator::None,2,Tokens::none},//o
			{Indicator::None,2,Tokens::none},//p
			{Indicator::None,2,Tokens::none},//q
			{Indicator::None,2,Tokens::none},//r
			{Indicator::None,2,Tokens::none},//s
			{Indicator::None,2,Tokens::none},//t
			{Indicator::None,2,Tokens::none},//u
			{Indicator::None,2,Tokens::none},//v
			{Indicator::None,2,Tokens::none},//w
			{Indicator::None,2,Tokens::none},//x
			{Indicator::None,2,Tokens::none},//y
			{Indicator::None,2,Tokens::none},//z
			{Indicator::None,2,Tokens::none},//{
			{Indicator::None,2,Tokens::none},//|
			{Indicator::None,2,Tokens::none},//}
			{Indicator::None,2,Tokens::none},//~
			{Indicator::Reject,0,Tokens::none},
		},
		//2 : '(char)('?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Accept_Inmediatly,1,Tokens::char_literal},//'
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
	};
}

#endif