
#ifndef OCTETOS_CC_TT_NUMBERS_HH
#define OCTETOS_CC_TT_NUMBERS_HH


/*
 * Copyright (C) 2022 Azael Reyes <azael.devel@gmail.com>
 * 
 * octetos-CC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * octetos-CC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#define LENGTH_TT(TABLE) sizeof (TABLE) / sizeof (TABLE[0])
#define TABLE(T) T,sizeof (T) / sizeof (T[0])

#include "../tt.hh"


namespace oct::cc::tt
{
	
	static const a::Transition Interger[][MAX_SIMBOLS] = {
	//0
		{
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},	
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Prefix_Accept,0},// ' '
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Accept,1},//0
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},//9
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//A
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//Z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//_
			{Indicator::Reject,0},
			{Indicator::Reject,0},//a
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
		},
	//1
		{
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},	
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Accept,1},//0
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},
			{Indicator::Accept,1},//9
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//A
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//Z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//_
			{Indicator::Reject,0},
			{Indicator::Reject,0},//a
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
		}
	};

	static const a::Transition Integer_0x[][tt::MAX_SIMBOLS] = {
	//0
		{
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//tab
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},	
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//' '
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::None,1},//0
			{Indicator::Reject,0},//1
			{Indicator::Reject,0},//2
			{Indicator::Reject,0},//3
			{Indicator::Reject,0},//4
			{Indicator::Reject,0},//5
			{Indicator::Reject,0},//6
			{Indicator::Reject,0},//7
			{Indicator::Reject,0},//8
			{Indicator::Reject,0},//9
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//A
			{Indicator::Reject,0},//B
			{Indicator::Reject,0},//C
			{Indicator::Reject,0},//D
			{Indicator::Reject,0},//E
			{Indicator::Reject,0},//F
			{Indicator::Reject,0},//G
			{Indicator::Reject,0},//H
			{Indicator::Reject,0},//I
			{Indicator::Reject,0},//J
			{Indicator::Reject,0},//K
			{Indicator::Reject,0},//L
			{Indicator::Reject,0},//M
			{Indicator::Reject,0},//N
			{Indicator::Reject,0},//O
			{Indicator::Reject,0},//P
			{Indicator::Reject,0},//Q
			{Indicator::Reject,0},//R
			{Indicator::Reject,0},//S
			{Indicator::Reject,0},//T
			{Indicator::Reject,0},//U
			{Indicator::Reject,0},//V
			{Indicator::Reject,0},//W
			{Indicator::Reject,0},//X
			{Indicator::Reject,0},//Y
			{Indicator::Reject,0},//Z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//_
			{Indicator::Reject,0},
			{Indicator::Reject,0},//a
			{Indicator::Reject,0},//b
			{Indicator::Reject,0},//c
			{Indicator::Reject,0},//d
			{Indicator::Reject,0},//e
			{Indicator::Reject,0},//f
			{Indicator::Reject,0},//g
			{Indicator::Reject,0},//h
			{Indicator::Reject,0},//i
			{Indicator::Reject,0},//j
			{Indicator::Reject,0},//k
			{Indicator::Reject,0},//l
			{Indicator::Reject,0},//m
			{Indicator::Reject,0},//n
			{Indicator::Reject,0},//o
			{Indicator::Reject,0},//p
			{Indicator::Reject,0},//q
			{Indicator::Reject,0},//r
			{Indicator::Reject,0},//s
			{Indicator::Reject,0},//t
			{Indicator::Reject,0},//u
			{Indicator::Reject,0},//v
			{Indicator::Reject,0},//w
			{Indicator::Reject,0},//x
			{Indicator::Reject,0},//y
			{Indicator::Reject,0},//z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
		},
		// 1 : x
		{
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//tab
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},	
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//' '
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//0
			{Indicator::Reject,0},//1
			{Indicator::Reject,0},//2
			{Indicator::Reject,0},//3
			{Indicator::Reject,0},//4
			{Indicator::Reject,0},//5
			{Indicator::Reject,0},//6
			{Indicator::Reject,0},//7
			{Indicator::Reject,0},//8
			{Indicator::Reject,0},//9
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//A
			{Indicator::Reject,0},//B
			{Indicator::Reject,0},//C
			{Indicator::Reject,0},//D
			{Indicator::Reject,0},//E
			{Indicator::Reject,0},//F
			{Indicator::Reject,0},//G
			{Indicator::Reject,0},//H
			{Indicator::Reject,0},//I
			{Indicator::Reject,0},//J
			{Indicator::Reject,0},//K
			{Indicator::Reject,0},//L
			{Indicator::Reject,0},//M
			{Indicator::Reject,0},//N
			{Indicator::Reject,0},//O
			{Indicator::Reject,0},//P
			{Indicator::Reject,0},//Q
			{Indicator::Reject,0},//R
			{Indicator::Reject,0},//S
			{Indicator::Reject,0},//T
			{Indicator::Reject,0},//U
			{Indicator::Reject,0},//V
			{Indicator::Reject,0},//W
			{Indicator::Reject,0},//X
			{Indicator::Reject,0},//Y
			{Indicator::Reject,0},//Z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//_
			{Indicator::Reject,0},
			{Indicator::Reject,0},//a
			{Indicator::Reject,0},//b
			{Indicator::Reject,0},//c
			{Indicator::Reject,0},//d
			{Indicator::Reject,0},//e
			{Indicator::Reject,0},//f
			{Indicator::Reject,0},//g
			{Indicator::Reject,0},//h
			{Indicator::Reject,0},//i
			{Indicator::Reject,0},//j
			{Indicator::Reject,0},//k
			{Indicator::Reject,0},//l
			{Indicator::Reject,0},//m
			{Indicator::Reject,0},//n
			{Indicator::Reject,0},//o
			{Indicator::Reject,0},//p
			{Indicator::Reject,0},//q
			{Indicator::Reject,0},//r
			{Indicator::Reject,0},//s
			{Indicator::Reject,0},//t
			{Indicator::Reject,0},//u
			{Indicator::Reject,0},//v
			{Indicator::Reject,0},//w
			{Indicator::None,2},//x
			{Indicator::Reject,0},//y
			{Indicator::Reject,0},//z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
		},
		//2 : ae10		
		{
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Prefix_Accept,0},//tab
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},	
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Prefix_Accept,0},//' '
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Accept,2},//0
			{Indicator::Accept,2},//1
			{Indicator::Accept,2},//2
			{Indicator::Accept,2},//3
			{Indicator::Accept,2},//4
			{Indicator::Accept,2},//5
			{Indicator::Accept,2},//6
			{Indicator::Accept,2},//7
			{Indicator::Accept,2},//8
			{Indicator::Accept,2},//9
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Accept,2},//A
			{Indicator::Accept,2},//B
			{Indicator::Accept,2},//C
			{Indicator::Accept,2},//D
			{Indicator::Accept,2},//E
			{Indicator::Accept,2},//F
			{Indicator::Reject,0},//G
			{Indicator::Reject,0},//H
			{Indicator::Reject,0},//I
			{Indicator::Reject,0},//J
			{Indicator::Reject,0},//K
			{Indicator::Reject,0},//L
			{Indicator::Reject,0},//M
			{Indicator::Reject,0},//N
			{Indicator::Reject,0},//O
			{Indicator::Reject,0},//P
			{Indicator::Reject,0},//Q
			{Indicator::Reject,0},//R
			{Indicator::Reject,0},//S
			{Indicator::Reject,0},//T
			{Indicator::Reject,0},//U
			{Indicator::Reject,0},//V
			{Indicator::Reject,0},//W
			{Indicator::Reject,0},//X
			{Indicator::Reject,0},//Y
			{Indicator::Reject,0},//Z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},//_
			{Indicator::Reject,0},
			{Indicator::Accept,2},//a
			{Indicator::Accept,2},//b
			{Indicator::Accept,2},//c
			{Indicator::Accept,2},//d
			{Indicator::Accept,2},//e
			{Indicator::Accept,2},//f
			{Indicator::Reject,0},//g
			{Indicator::Reject,0},//h
			{Indicator::Reject,0},//i
			{Indicator::Reject,0},//j
			{Indicator::Reject,0},//k
			{Indicator::Reject,0},//l
			{Indicator::Reject,0},//m
			{Indicator::Reject,0},//n
			{Indicator::Reject,0},//o
			{Indicator::Reject,0},//p
			{Indicator::Reject,0},//q
			{Indicator::Reject,0},//r
			{Indicator::Reject,0},//s
			{Indicator::Reject,0},//t
			{Indicator::Reject,0},//u
			{Indicator::Reject,0},//v
			{Indicator::Reject,0},//w
			{Indicator::Reject,0},//x
			{Indicator::Reject,0},//y
			{Indicator::Reject,0},//z
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
			{Indicator::Reject,0},
		},
	};

}

#endif