

#ifndef OCTETOS_CC_TT_A_LEX_HH
#define OCTETOS_CC_TT_A_LEX_HH

/*
 * Copyright (C) 2022 Azael Reyes <azael.devel@gmail.com>
 * 
 * CC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * CC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "../../tt.hh" 

//transition table
namespace oct::cc::tt::a::lex
{
	
	static const tt::a::Transition file[][tt::MAX_SIMBOLS] = {
	//0
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Eat,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Eat,0,(Word)Tokens::none},//new line
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Eat,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::None,8,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::None,1,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		// 2 : s(e?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::None,2,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		// 2 : se(c?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::None,3,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//3 : sec(t?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::None,4,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//4:sect(i?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::None,5,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//5:secti(o?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::None,6,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//6 : sectio(n?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Accept,7,(Word)Tokens::file_section},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//7:section(|<--)?
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Prefix_Accept,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Prefix_Accept,0,(Word)Tokens::none},//new line
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Prefix_Accept,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Prefix_Accept,0,(Word)Tokens::none},//{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//8 : c(o?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//new line
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::None,9,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//9:co(d?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//new line
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::None,10,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//10:cod(e?)
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//new line
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Accept,11,(Word)Tokens::file_code},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
		//11 : code(|<--)?
		{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Prefix_Accept,0,(Word)Tokens::none},//tab
			{cc::tt::Indicator::Prefix_Accept,0,(Word)Tokens::none},//new line
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},	
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Prefix_Accept,0,(Word)Tokens::none},//' '
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//0
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//1
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//2
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//3
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//4
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//5
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//6
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//7
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//8
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//9
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//:
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//;
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//<
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//=
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//>
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//?
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//@
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//A
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//B
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//C
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//D
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//E
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//F
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//G
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//H
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//I
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//J
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//K
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//L
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//M
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//N
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//O
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//P
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//R
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//S
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//T
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//U
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//V
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//W
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//X
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//Z
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//_
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//a
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//b
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//c
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//d
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//e
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//f
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//g
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//h
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//i
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//j
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//k
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//l
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//m
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//n
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//o
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//p
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//q
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//r
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//s
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//t
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//u
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//v
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//w
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//x
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//y
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},//z
			{cc::tt::Indicator::Prefix_Accept,0,(Word)Tokens::none},//{
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
			{cc::tt::Indicator::Reject,0,(Word)Tokens::none},
		},
	};

}




#endif