

#ifndef OCTETOS_CC_TT_A_LEX_HH
#define OCTETOS_CC_TT_A_LEX_HH

/*
 * Copyright (C) 2022 Azael Reyes <azael.devel@gmail.com>
 * 
 * CC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * CC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "../../tt.hh" 

//transition table
namespace oct::cc::tt::a::lex
{
	
	static const tt::a::Transition file[][tt::MAX_SIMBOLS] = {
	//0
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Prev_Eat,0,Tokens::none},//tab
			{Indicator::Prev_Eat,0,Tokens::none},//new line
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Prev_Eat,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::None,8,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::None,1,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		// 2 : s(e?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::None,2,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		// 2 : se(c?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::None,3,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//3 : sec(t?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::None,4,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//4:sect(i?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::None,5,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//5:secti(o?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::None,6,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//6 : sectio(n?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Accept,7,Tokens::file_section},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//7:section(|<--)?
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Prefix_Accept,0,Tokens::none},//tab
			{Indicator::Prefix_Accept,0,Tokens::none},//new line
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Prefix_Accept,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Prefix_Accept,0,Tokens::none},//{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//8 : c(o?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},//new line
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::None,9,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//9:co(d?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},//new line
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::None,10,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//10:cod(e?)
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//tab
			{Indicator::Reject,0,Tokens::none},//new line
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Accept,11,Tokens::file_code},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
		//11 : code(|<--)?
		{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Prefix_Accept,0,Tokens::none},//tab
			{Indicator::Prefix_Accept,0,Tokens::none},//new line
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},	
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Prefix_Accept,0,Tokens::none},//' '
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//0
			{Indicator::Reject,0,Tokens::none},//1
			{Indicator::Reject,0,Tokens::none},//2
			{Indicator::Reject,0,Tokens::none},//3
			{Indicator::Reject,0,Tokens::none},//4
			{Indicator::Reject,0,Tokens::none},//5
			{Indicator::Reject,0,Tokens::none},//6
			{Indicator::Reject,0,Tokens::none},//7
			{Indicator::Reject,0,Tokens::none},//8
			{Indicator::Reject,0,Tokens::none},//9
			{Indicator::Reject,0,Tokens::none},//:
			{Indicator::Reject,0,Tokens::none},//;
			{Indicator::Reject,0,Tokens::none},//<
			{Indicator::Reject,0,Tokens::none},//=
			{Indicator::Reject,0,Tokens::none},//>
			{Indicator::Reject,0,Tokens::none},//?
			{Indicator::Reject,0,Tokens::none},//@
			{Indicator::Reject,0,Tokens::none},//A
			{Indicator::Reject,0,Tokens::none},//B
			{Indicator::Reject,0,Tokens::none},//C
			{Indicator::Reject,0,Tokens::none},//D
			{Indicator::Reject,0,Tokens::none},//E
			{Indicator::Reject,0,Tokens::none},//F
			{Indicator::Reject,0,Tokens::none},//G
			{Indicator::Reject,0,Tokens::none},//H
			{Indicator::Reject,0,Tokens::none},//I
			{Indicator::Reject,0,Tokens::none},//J
			{Indicator::Reject,0,Tokens::none},//K
			{Indicator::Reject,0,Tokens::none},//L
			{Indicator::Reject,0,Tokens::none},//M
			{Indicator::Reject,0,Tokens::none},//N
			{Indicator::Reject,0,Tokens::none},//O
			{Indicator::Reject,0,Tokens::none},//P
			{Indicator::Reject,0,Tokens::none},//Q
			{Indicator::Reject,0,Tokens::none},//R
			{Indicator::Reject,0,Tokens::none},//S
			{Indicator::Reject,0,Tokens::none},//T
			{Indicator::Reject,0,Tokens::none},//U
			{Indicator::Reject,0,Tokens::none},//V
			{Indicator::Reject,0,Tokens::none},//W
			{Indicator::Reject,0,Tokens::none},//X
			{Indicator::Reject,0,Tokens::none},//Y
			{Indicator::Reject,0,Tokens::none},//Z
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//_
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},//a
			{Indicator::Reject,0,Tokens::none},//b
			{Indicator::Reject,0,Tokens::none},//c
			{Indicator::Reject,0,Tokens::none},//d
			{Indicator::Reject,0,Tokens::none},//e
			{Indicator::Reject,0,Tokens::none},//f
			{Indicator::Reject,0,Tokens::none},//g
			{Indicator::Reject,0,Tokens::none},//h
			{Indicator::Reject,0,Tokens::none},//i
			{Indicator::Reject,0,Tokens::none},//j
			{Indicator::Reject,0,Tokens::none},//k
			{Indicator::Reject,0,Tokens::none},//l
			{Indicator::Reject,0,Tokens::none},//m
			{Indicator::Reject,0,Tokens::none},//n
			{Indicator::Reject,0,Tokens::none},//o
			{Indicator::Reject,0,Tokens::none},//p
			{Indicator::Reject,0,Tokens::none},//q
			{Indicator::Reject,0,Tokens::none},//r
			{Indicator::Reject,0,Tokens::none},//s
			{Indicator::Reject,0,Tokens::none},//t
			{Indicator::Reject,0,Tokens::none},//u
			{Indicator::Reject,0,Tokens::none},//v
			{Indicator::Reject,0,Tokens::none},//w
			{Indicator::Reject,0,Tokens::none},//x
			{Indicator::Reject,0,Tokens::none},//y
			{Indicator::Reject,0,Tokens::none},//z
			{Indicator::Prefix_Accept,0,Tokens::none},//{
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
			{Indicator::Reject,0,Tokens::none},
		},
	};

}




#endif